import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Toaster } from "@/components/ui/sonner" // Import du nouveau composant Sonner
import "./globals.css"
import Script from "next/script"

<Toaster position="top-right" /> //////////////


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Catchub-app",
  description: "Generated by create next app",
  // Vous pouvez ajouter d'autres métadonnées ici
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 👉 Balise Google tag ici */}
  
 
        {children}
        <Toaster
          position="top-right"
          richColors
          closeButton
          expand
          visibleToasts={3}
          toastOptions={{
            classNames: {
              toast: "font-sans", // Utilise vos polices Geist
            },
          }}
        />
      </body>
    </html>
  )
}
